export const CHILD_ROUTES = {
  docs: {
    colors: "colors",
    colorUsage: "color-usage",
    typography: "typography",
    buttons: "buttons",
    cards: "cards",
    lists: "lists",
    shadows: "shadows",
    modals: "modals",
    toasts: "toasts",
    navbarpage:"navbar",
    paginationpage:"pagination",
    breadcrumpspage:"breadcrumps",
    sidebarpage:"sidebar",
    skeleton: "skeleton",
    chips: "chips",
    accordion: "accordion",
    counter: "counter",
    darkMode: "darkMode",
    notification: "notification",
    label: "label",
    input: "input",
    checkbox: "checkbox",
    textarea: "textarea",
    toggle: "toggle",
    radioButton: "radio-button",
    morphed: "morphed",
    otp: "otp",
    select: "select",
    cli: "clitabs",
  },
} as const;

export const ROUTES = {
  home: "/",
  dump: "/dump",
  showcase: "/showcase",
  docs: "/docs",
  colorsDocs: `/docs/${CHILD_ROUTES.docs.colors}`,
  ColorUsageDocs: `/docs/${CHILD_ROUTES.docs.colorUsage}`,
  typographyDocs: `/docs/${CHILD_ROUTES.docs.typography}`,
  buttonsDocs: `/docs/${CHILD_ROUTES.docs.buttons}`,
  cardsDocs: `/docs/${CHILD_ROUTES.docs.cards}`,
  listsDocs: `/docs/${CHILD_ROUTES.docs.lists}`,
  shadowsDocs: `/docs/${CHILD_ROUTES.docs.shadows}`,
  modalsDocs: `/docs/${CHILD_ROUTES.docs.modals}`,
  toastsDocs: `/docs/${CHILD_ROUTES.docs.toasts}`,
  NavbarPage:`/docs/${CHILD_ROUTES.docs.navbarpage}`,
  PaginationPage:`/docs/${CHILD_ROUTES.docs.paginationpage}`,
  BreadcrumbsPage:`/docs/${CHILD_ROUTES.docs.breadcrumpspage}`,
  SidebarPagePage:`/docs/${CHILD_ROUTES.docs.sidebarpage}`,
  skeletonDocs: `/docs/${CHILD_ROUTES.docs.skeleton}`,
  chipsDocs: `/docs/${CHILD_ROUTES.docs.chips}`,
  accordionDocs: `/docs/${CHILD_ROUTES.docs.accordion}`,
  counterDocs: `/docs/${CHILD_ROUTES.docs.counter}`,
  darkModeDocs: `/docs/${CHILD_ROUTES.docs.darkMode}`,
  notificationDocs: `/docs/${CHILD_ROUTES.docs.notification}`,
  labelDocs: `/docs/${CHILD_ROUTES.docs.label}`,
  inputDocs: `/docs/${CHILD_ROUTES.docs.input}`,
  textareaDocs: `/docs/${CHILD_ROUTES.docs.textarea}`,
  toggleDocs: `/docs/${CHILD_ROUTES.docs.toggle}`,
  radioButtonDocs: `/docs/${CHILD_ROUTES.docs.radioButton}`,
  checkboxDocs: `/docs/${CHILD_ROUTES.docs.checkbox}`,
  selectDocs: `/docs/${CHILD_ROUTES.docs.select}`,
  morphedDocs: `/docs/${CHILD_ROUTES.docs.morphed}`,
  otpDocs: `/docs/${CHILD_ROUTES.docs.otp}`,
  cliDocs: `/docs/${CHILD_ROUTES.docs.cli}`,
} as const;
